[package]
name = "cd_gpuchart"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[dependencies]
wgpu = { version = "26.0.1", features = ["webgpu"] }   # add "webgl" later for fallback
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window","Document","HtmlCanvasElement","Gpu","GpuCanvasContext"] }
bytemuck = { version = "1", features = ["derive"] }
console_error_panic_hook = "0.1"
wasm-logger = "0.2"
log = "0.4"
anyhow = "1.0.89"
once_cell = "1.21.3"
